[package]
name = "ddk-payouts"
version = "0.0.12"
authors = ["benny b <ben@bitcoinbay.foundation>"]
description = "Library to build payout functions for DLC contracts."
license = "MIT"
repository = "https://github.com/bennyhodl/dlcdevkit"
edition = "2021"

[dependencies]
# dlc = { version = "0.6.0", git = "https://github.com/bennyhodl/rust-dlc", branch = "bitcoin-32", features = ["use-serde"] }
# dlc-manager = { version = "0.6.0", git = "https://github.com/bennyhodl/rust-dlc", branch = "bitcoin-32", features = ["use-serde"] }
# dlc-messages = { version = "0.6.0", git = "https://github.com/bennyhodl/rust-dlc", branch = "bitcoin-32", features = [ "use-serde"] }
# dlc-trie = { version = "0.6.0", git = "https://github.com/bennyhodl/rust-dlc", branch = "bitcoin-32", features = ["use-serde"] }
dlc = { version = "0.6.0", git = "https://github.com/bennyhodl/rust-dlc", branch = "better-error-messages", features = ["use-serde"] }
dlc-manager = { version = "0.6.0", git = "https://github.com/bennyhodl/rust-dlc", branch = "better-error-messages", features = ["use-serde"] }
dlc-messages = { version = "0.6.0", git = "https://github.com/bennyhodl/rust-dlc", branch = "better-error-messages", features = [ "use-serde"] }
dlc-trie = { version = "0.6.0", git = "https://github.com/bennyhodl/rust-dlc", branch = "better-error-messages", features = ["use-serde"] }
# dlc-trie = { version = "0.5.0", features = [ "use-serde"] }
# dlc = { version = "0.5.0", features = [ "use-serde"] }
# dlc-manager = { version = "0.5.0", features = [ "use-serde"] }
# dlc-messages = { version = "0.5.0", features = [ "use-serde"] }
bitcoin = "0.32.2"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
anyhow = "1.0.86"
